### ISSUE TITLE
Get rid of 'overshoot' on right side of map

### ISSUE THREAD

**Issue by tomvantilburg** [RubioV/json_test#25]
likely some css thingy...

**Comment by tomvantilburg** [comment]
was caused by photo input element. Moved it a bit to the left and now all is fine...

**Comment by RubioV** [comment]
I'm not sure what the problem was in this case, but it seems the fix has some unintended effects:

```
#camerainput{
    position: absolute;
    bottom: 0;
 -  right: 0;
 +  right: 75px;
    margin: 0;
```

This results in the form input being in a different place than the camera button. Discuss this with Tom.
