### ISSUE TITLE
in cow-element addPhoto: Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by RubioV** [RubioV/json_test#27]
https://github.com/RubioV/json_test/blob/1a808c7414329c80b1932653f80cd924e33fdebe/elements/cow-element.html#L135

**Comment by tomvantilburg** [comment]
Likely because groupid was missing, fixed this in a later commit.

**Comment by RubioV** [comment]
Caused by an incomplete merge of Tom's changes (e08fe14a812d4522d53811010dc03fbfbadfbb47).
