### ISSUE TITLE
Get photo upload working

### ISSUE THREAD

**Issue by RubioV** [RubioV/json_test#3]

**Comment by tomvantilburg** [comment]
Multi phase approach:
1. Create cow-item with metadata
2. Upload photo with name based on cow id
3. Add success tag to cow-item on successful upload

**Comment by RubioV** [comment]
Mostly working in https://github.com/RubioV/json_test/commit/b1e8c209c6bcaa6fddfe234e019a15399d0e93b6. Remaining work:
- get file id from POST response and share it via COW
- Resize photo before upload to save bandwidth (https://github.com/RubioV/json_test/issues/21)
- Show temporary photo popups of other users (https://github.com/RubioV/json_test/issues/22)
