### ISSUE TITLE
enable user deltas 

### ISSUE THREAD

**Issue by tomvantilburg** [RubioV/json_test#30]
Both on webclients and superpeer. To do it nicely cow has to be patched.

**Comment by tomvantilburg** [comment]
Wontfix. Te veel risico omdat we daar nooit mee getest hebben.

**Comment by RubioV** [comment]
Reopened this as it seems like user deltas are being kept at the moment. Check this.

**Comment by RubioV** [comment]
Local copy of cow had this enabled.
