### ISSUE TITLE
Labels become white when zoomed out

### ISSUE THREAD

**Issue by RubioV** [RubioV/json_test#32]

**Comment by tomvantilburg** [comment]
This is a mappu thing.

**Comment by tomvantilburg** [comment]
Made the text more transparent when zooming out.

**Comment by tomvantilburg** [comment]
Nog ff naar kijken,.... het zou mogelijk moeten zijn om de labels helemaal weg te halen bij uitzoomen.

**Comment by tomvantilburg** [comment]
Should be fixed with #44
